//preforms semantica analysis on an AST (generated by parser)
public class SemanticAnalysis 
{
    public void CheckAssignments(ProgramNode p_Program) throws SyntaxErrorException
    {
        for(FunctionNode functionindex : (p_Program.getfunctions()).values())
        {
            for(StatementNode stateindex: functionindex.getStatments())
            {
                if(stateindex instanceof AssignmentNode)
                {
                    Node leftside = ((AssignmentNode)stateindex).getTarget();
                    Node rightside = ((AssignmentNode)stateindex).getValue();

                    if(rightside instanceof MathOpNode)
                    {
                        CheckAssignments(p_Program);
                    }
                    if(!(leftside.getClass().toString() == rightside.getClass().toString()))
                        throw new SyntaxErrorException("Invalid assigment, types do not match: " + leftside.getClass().toString()+ " " + rightside.getClass().toString());
                }
            }
        }
    }
}
